Repository PLUB2022/PLUB-iOS, pull requests merged in 2023-03, with the labels that each got.

#182 [FEAT] 모집관련 셀 그라디언트 추가
  PLUB/Sources/Views/Home/Cell/SelectCategory/SelectedCategoryChartCollectionViewCell.swift
  PLUB/Sources/Views/Home/Cell/SelectCategory/SelectedCategoryGridCollectionViewCell.swift
  PLUB/Sources/Views/Home/RegisterInterestViewController.swift
Labels: 😎 Enhancement, 🍎 ConfigureUI, 🏠 Home, D+1

#183 [FEAT] 모임 일정 리스트 기능 구현
  PLUB.xcodeproj/project.pbxproj
  PLUB/Assets.xcassets/Meeting/MeetingSchedule/clockBlack16.imageset/Contents.json
  PLUB/Assets.xcassets/Meeting/MeetingSchedule/clockBlack16.imageset/clockBlack.png
  PLUB/Assets.xcassets/Meeting/MeetingSchedule/clockBlack16.imageset/clockBlack@2x.png
  PLUB/Assets.xcassets/Meeting/MeetingSchedule/clockBlack16.imageset/clockBlack@3x.png
  PLUB/Assets.xcassets/Meeting/MeetingSchedule/locationBlack16.imageset/Contents.json
  PLUB/Assets.xcassets/Meeting/MeetingSchedule/locationBlack16.imageset/locationBlack16.png
  PLUB/Assets.xcassets/Meeting/MeetingSchedule/locationBlack16.imageset/locationBlack16@2x.png
  PLUB/Assets.xcassets/Meeting/MeetingSchedule/locationBlack16.imageset/locationBlack16@3x.png
  PLUB/Assets.xcassets/Meeting/MeetingSchedule/pinGray.imageset/Contents.json
  PLUB/Assets.xcassets/Meeting/MeetingSchedule/pinGray.imageset/pinGray.png
  PLUB/Assets.xcassets/Meeting/MeetingSchedule/pinGray.imageset/pinGray@2x.png
  PLUB/Assets.xcassets/Meeting/MeetingSchedule/pinGray.imageset/pinGray@3x.png
  PLUB/Assets.xcassets/Meeting/MeetingSchedule/pointBlack.imageset/Contents.json
  PLUB/Assets.xcassets/Meeting/MeetingSchedule/pointBlack.imageset/pointBlack.png
  PLUB/Assets.xcassets/Meeting/MeetingSchedule/pointBlack.imageset/pointBlack@2x.png
  PLUB/Assets.xcassets/Meeting/MeetingSchedule/pointBlack.imageset/pointBlack@3x.png
  PLUB/Assets.xcassets/Meeting/MeetingSchedule/pointGray.imageset/Contents.json
  PLUB/Assets.xcassets/Meeting/MeetingSchedule/pointGray.imageset/pointGray.png
  PLUB/Assets.xcassets/Meeting/MeetingSchedule/pointGray.imageset/pointGray@2x.png
  PLUB/Assets.xcassets/Meeting/MeetingSchedule/pointGray.imageset/pointGray@3x.png
  PLUB/Assets.xcassets/Meeting/MeetingSchedule/scheduleBlack.imageset/Contents.json
  PLUB/Assets.xcassets/Meeting/MeetingSchedule/scheduleBlack.imageset/calendarBlack.png
  PLUB/Assets.xcassets/Meeting/MeetingSchedule/scheduleBlack.imageset/calendarBlack@2x.png
  PLUB/Assets.xcassets/Meeting/MeetingSchedule/scheduleBlack.imageset/calendarBlack@3x.png
  PLUB/Assets.xcassets/Meeting/MeetingSchedule/scheduleBlack16.imageset/Contents.json
  PLUB/Assets.xcassets/Meeting/MeetingSchedule/scheduleBlack16.imageset/scheduleBlack16.png
  PLUB/Assets.xcassets/Meeting/MeetingSchedule/scheduleBlack16.imageset/scheduleBlack16@2x.png
  PLUB/Assets.xcassets/Meeting/MeetingSchedule/scheduleBlack16.imageset/scheduleBlack16@3x.png
  PLUB/Sources/Models/Schedule/Response/ScheduleListResponse.swift
  PLUB/Sources/Network/Routers/ScheduleRouter.swift
  PLUB/Sources/Network/Services/ScheduleService.swift
  PLUB/Sources/Views/Home/MeetingSchedule/Cell/ScheduleTableViewCell.swift
  PLUB/Sources/Views/Home/MeetingSchedule/Component/AddScheduleControl.swift
  PLUB/Sources/Views/Home/MeetingSchedule/Component/ScheduleDateView.swift
  PLUB/Sources/Views/Home/MeetingSchedule/Component/ScheduleDetailContentView.swift
  PLUB/Sources/Views/Home/MeetingSchedule/Component/ScheduleTopView.swift
  PLUB/Sources/Views/Home/MeetingSchedule/MeetingScheduleViewController.swift
  PLUB/Sources/Views/Home/MeetingSchedule/MeetingScheduleViewModel.swift
  PLUB/Sources/Views/Meeting/Schedule/CreateSchedule/CreateScheduleViewController.swift
Labels: 🍎 ConfigureUI, 👨‍👩‍👧‍👦 Meeting, D+1

#189 [REFACTOR] 게시판 API - Cursor based pagination
  PLUB/Sources/Models/Feeds/FeedsContent.swift
  PLUB/Sources/Models/Feeds/Response/FeedsPaginatedDataResponse.swift
  PLUB/Sources/Network/Routers/FeedsRouter.swift
  PLUB/Sources/Network/Services/FeedsService.swift
Labels: 😎 Enhancement, D+0

#193 [ADD] GoogleService-Info 파일 추가
  PLUB/GoogleService-Info.plist
Labels: 🔥hotfix

#190 [FEAT] 내모임 UI 구현
  PLUB.xcodeproj/project.pbxproj
  PLUB/Sources/Models/Meeting/Response/MyMeetingResponse.swift
  PLUB/Sources/Models/Schedule/Request/CreateScheduleRequest.swift
  PLUB/Sources/Network/Routers/MeetingRouter.swift
  PLUB/Sources/Network/Services/MeetingService.swift
  PLUB/Sources/Views/Meeting/Cell/MeetingCollectionViewCell.swift
  PLUB/Sources/Views/Meeting/CreateMeeting/ViewController/MeetingCreateSuccessViewController.swift
  PLUB/Sources/Views/Meeting/CreateMeeting/ViewController/MeetingQuestionViewController.swift
  PLUB/Sources/Views/Meeting/MeetingViewController.swift
  PLUB/Sources/Views/Meeting/MeetingViewModel.swift
  PLUB/Sources/Views/Meeting/Schedule/CreateSchedule/Component/ScheduleAlarmView.swift
  PLUB/Sources/Views/Meeting/Schedule/CreateSchedule/CreateScheduleViewModel.swift
Labels: 🍎 ConfigureUI, 👨‍👩‍👧‍👦 Meeting, D+1

#194 [FEAT] 메인페이지 화면 UI 구현
  PLUB.xcodeproj/project.pbxproj
  PLUB/Assets.xcassets/Home/Component/photoStackBlack.imageset/Component 1.png
  PLUB/Assets.xcassets/Home/Component/photoStackBlack.imageset/Component 1@2x.png
  PLUB/Assets.xcassets/Home/Component/photoStackBlack.imageset/Component 1@3x.png
  PLUB/Assets.xcassets/Home/Component/photoStackBlack.imageset/Contents.json
  PLUB/Assets.xcassets/Home/Component/photoStackWhite.imageset/Component 4.png
  PLUB/Assets.xcassets/Home/Component/photoStackWhite.imageset/Component 4@2x.png
  PLUB/Assets.xcassets/Home/Component/photoStackWhite.imageset/Component 4@3x.png
  PLUB/Assets.xcassets/Home/Component/photoStackWhite.imageset/Contents.json
  PLUB/Assets.xcassets/Home/Component/speakerBlack.imageset/Component 1.png
  PLUB/Assets.xcassets/Home/Component/speakerBlack.imageset/Component 1@2x.png
  PLUB/Assets.xcassets/Home/Component/speakerBlack.imageset/Component 1@3x.png
  PLUB/Assets.xcassets/Home/Component/speakerBlack.imageset/Contents.json
  PLUB/Assets.xcassets/Home/Component/speakerWhite.imageset/Component 3.png
  PLUB/Assets.xcassets/Home/Component/speakerWhite.imageset/Component 3@2x.png
  PLUB/Assets.xcassets/Home/Component/speakerWhite.imageset/Component 3@3x.png
  PLUB/Assets.xcassets/Home/Component/speakerWhite.imageset/Contents.json
  PLUB/Assets.xcassets/Home/Component/verticalEllipsisBlack.imageset/Component 2.png
  PLUB/Assets.xcassets/Home/Component/verticalEllipsisBlack.imageset/Component 2@2x.png
  PLUB/Assets.xcassets/Home/Component/verticalEllipsisBlack.imageset/Component 2@3x.png
  PLUB/Assets.xcassets/Home/Component/verticalEllipsisBlack.imageset/Contents.json
  PLUB/Assets.xcassets/Home/Component/verticalEllipsisWhite.imageset/Component 2.png
  PLUB/Assets.xcassets/Home/Component/verticalEllipsisWhite.imageset/Component 2@2x.png
  PLUB/Assets.xcassets/Home/Component/verticalEllipsisWhite.imageset/Component 2@3x.png
  PLUB/Assets.xcassets/Home/Component/verticalEllipsisWhite.imageset/Contents.json
  PLUB/Assets.xcassets/Home/Indicator/leftIndicatorWhite.imageset/Component 1.png
  PLUB/Assets.xcassets/Home/Indicator/leftIndicatorWhite.imageset/Component 1@2x.png
  PLUB/Assets.xcassets/Home/Indicator/leftIndicatorWhite.imageset/Component 1@3x.png
  PLUB/Assets.xcassets/Home/Indicator/leftIndicatorWhite.imageset/Contents.json
  PLUB/Assets.xcassets/Home/Indicator/rightIndicatorGray.imageset/Contents.json
  PLUB/Assets.xcassets/Home/Indicator/rightIndicatorGray.imageset/Frame 60.png
  PLUB/Assets.xcassets/Home/Indicator/rightIndicatorGray.imageset/Frame 60@2x.png
  PLUB/Assets.xcassets/Home/Indicator/rightIndicatorGray.imageset/Frame 60@3x.png
  PLUB/SceneDelegate.swift
  PLUB/Sources/Views/Home/BookmarkViewController.swift
  PLUB/Sources/Views/Home/HomeViewController.swift
  PLUB/Sources/Views/Home/MainPage/BoardViewController.swift
  PLUB/Sources/Views/Home/MainPage/Cell/BoardCollectionHeaderView.swift
  PLUB/Sources/Views/Home/MainPage/Component/ClipboardListView.swift
  PLUB/Sources/Views/Home/MainPage/Component/MainPageHeaderView.swift
  PLUB/Sources/Views/Home/MainPage/Component/MainPageNavigationView.swift
  PLUB/Sources/Views/Home/MainPage/MainPageViewController.swift
  PLUB/Sources/Views/Home/MainPage/MainPageViewModel.swift
  PLUB/Sources/Views/Home/MainPage/TodolistViewController.swift
  PLUB/Sources/Views/Home/MainPage/ViewModel/BoardViewModel.swift
  PLUB/Sources/Views/Home/SearchInputViewController.swift
Labels: 😎 Enhancement, 🍎 ConfigureUI

#187 [Network] 게시판 댓글 API 구현(Depend on. #189)
  PLUB.xcodeproj/project.pbxproj
  PLUB/Sources/Models/Feeds/CommentContent.swift
  PLUB/Sources/Models/Feeds/Response/FeedsPaginatedDataResponse.swift
  PLUB/Sources/Network/Routers/FeedsRouter.swift
  PLUB/Sources/Network/Services/FeedsService.swift
Labels: D+2, 🥳MainPage

#197 FeedsPaginatedDataResponse 수정
  PLUB/Sources/Models/Feeds/Response/FeedsPaginatedDataResponse.swift
Labels: D+2

#198 [FEAT] 모임 일정 > 참여자 리스트 기능 구현
  PLUB.xcodeproj/project.pbxproj
  PLUB/Configuration/Extensions/Ex+UIColor.swift
  PLUB/Sources/Models/Schedule/Request/AttendScheduleRequest.swift
  PLUB/Sources/Models/Schedule/Response/AttendScheduleResponse.swift
  PLUB/Sources/Models/Schedule/Response/ScheduleListResponse.swift
  PLUB/Sources/Network/Routers/ScheduleRouter.swift
  PLUB/Sources/Network/Services/ScheduleService.swift
  PLUB/Sources/Views/Home/Cell/DetailRecruitment/IntroduceTagCollectionViewCell.swift
  PLUB/Sources/Views/Home/Cell/DetailRecruitment/ParticipantCollectionViewCell.swift
  PLUB/Sources/Views/Home/MeetingSchedule/Cell/ScheduleTableViewCell.swift
  PLUB/Sources/Views/Home/MeetingSchedule/Component/ScheduleDateView.swift
  PLUB/Sources/Views/Home/MeetingSchedule/Component/ScheduleDetailContentView.swift
  PLUB/Sources/Views/Home/MeetingSchedule/MeetingScheduleViewController.swift
  PLUB/Sources/Views/Home/MeetingSchedule/MeetingScheduleViewModel.swift
  PLUB/Sources/Views/Home/MeetingSchedule/ScheduleParticipant/Cell/ScheduleParticipantCollectionViewCell.swift
  PLUB/Sources/Views/Home/MeetingSchedule/ScheduleParticipant/Component/ScheduleParticipantTopView.swift
  PLUB/Sources/Views/Home/MeetingSchedule/ScheduleParticipant/ScheduleParticipantViewController.swift
  PLUB/Sources/Views/Home/MeetingSchedule/ScheduleParticipant/ScheduleParticipantViewModel.swift
  PLUB/Sources/Views/Meeting/Schedule/CreateSchedule/CreateScheduleViewController.swift
  PLUB/Sources/Views/Meeting/Schedule/CreateSchedule/CreateScheduleViewModel.swift
Labels: 🍎 ConfigureUI, 👨‍👩‍👧‍👦 Meeting, D+2

#196 게시글 UI 구현
  PLUB.xcodeproj/project.pbxproj
  PLUB/Assets.xcassets/Home/Clipboard/fluentArrowReply.imageset/Contents.json
  PLUB/Assets.xcassets/Home/Clipboard/fluentArrowReply.imageset/fluentArrowReply.png
  PLUB/Assets.xcassets/Home/Clipboard/fluentArrowReply.imageset/fluentArrowReply@2x.png
  PLUB/Assets.xcassets/Home/Clipboard/fluentArrowReply.imageset/fluentArrowReply@3x.png
  PLUB/Assets.xcassets/Home/Clipboard/kebabMenu.imageset/Contents.json
  PLUB/Assets.xcassets/Home/Clipboard/kebabMenu.imageset/kebabMenu.png
  PLUB/Assets.xcassets/Home/Clipboard/kebabMenu.imageset/kebabMenu@2x.png
  PLUB/Assets.xcassets/Home/Clipboard/kebabMenu.imageset/kebabMenu@3x.png
  PLUB/Assets.xcassets/Home/Clipboard/meatballMenu.imageset/Contents.json
  PLUB/Assets.xcassets/Home/Clipboard/meatballMenu.imageset/meatballMenu.png
  PLUB/Assets.xcassets/Home/Clipboard/meatballMenu.imageset/meatballMenu@2x.png
  PLUB/Assets.xcassets/Home/Clipboard/meatballMenu.imageset/meatballMenu@3x.png
  PLUB/Sources/Views/Home/Clipboard/BoardDetailViewController.swift
  PLUB/Sources/Views/Home/Clipboard/Cell/BoardCollectionViewCell.swift
  PLUB/Sources/Views/Home/Clipboard/Cell/BoardDetailCollectionViewCell.swift
  PLUB/Sources/Views/Home/Clipboard/Component/BoardDetailCollectionHeaderView.swift
  PLUB/Sources/Views/Home/Clipboard/Model/BoardModel.swift
  PLUB/Sources/Views/Home/Clipboard/ViewModel/BoardDetailViewModel.swift
  PLUB/Sources/Views/Home/Clipboard/ViewModel/ClipboardViewModel.swift
Labels: 🍎 ConfigureUI, D+2

#201 [FIX] Navigation Pop Gesture Indicator
  PLUB.xcodeproj/project.pbxproj
  PLUB/Configuration/Base/BaseNavigationController.swift
  PLUB/Sources/Views/PLUBTabBarController.swift
Labels: 🐛 bug

#204 [REFACTOR] FIgma 디자인에 맞게 Font 설정
  PLUB/AppDelegate.swift
  PLUB/Configuration/Extensions/Ex+UIFont.swift
  PLUB/Sources/Views/Home/Cell/Search/SearchOutputHeaderView.swift
  PLUB/Sources/Views/Home/Component/RecruitmentFilterSlider.swift
  PLUB/Sources/Views/Home/MainPage/MainPageViewController.swift
  PLUB/Sources/Views/Login/ViewController/LoginViewController.swift
  PLUB/Sources/Views/Login/ViewController/ProfileViewController.swift
  PLUB/Sources/Views/Meeting/CreateMeeting/Cell/LocationTableViewCell.swift
  PLUB/Sources/Views/Meeting/CreateMeeting/Component/NoLocationView.swift
  PLUB/Sources/Views/Meeting/CreateMeeting/Component/SearchView.swift
  PLUB/Sources/Views/Meeting/EditMeeting/EditMeetingViewController.swift
  PLUB/Sources/Views/Meeting/Schedule/CreateSchedule/CreateScheduleViewController.swift
Labels: ♻️Refactoring

#205 [FEAT] Archive UI 구현
  PLUB.xcodeproj/project.pbxproj
  PLUB/Assets.xcassets/Home/Archive/Contents.json
  PLUB/Assets.xcassets/Home/Archive/photoLibrary.imageset/Contents.json
  PLUB/Assets.xcassets/Home/Archive/photoLibrary.imageset/photoLibrary.png
  PLUB/Assets.xcassets/Home/Archive/photoLibrary.imageset/photoLibrary@2x.png
  PLUB/Assets.xcassets/Home/Archive/photoLibrary.imageset/photoLibrary@3x.png
  PLUB/Assets.xcassets/Home/Archive/pointWhite.imageset/Contents.json
  PLUB/Assets.xcassets/Home/Archive/pointWhite.imageset/pointWhite.png
  PLUB/Assets.xcassets/Home/Archive/pointWhite.imageset/pointWhite@2x.png
  PLUB/Assets.xcassets/Home/Archive/pointWhite.imageset/pointWhite@3x.png
  PLUB/Configuration/Extensions/Ex+UIButton.swift
  PLUB/Sources/Views/Home/Archive/ArchiveCollectionViewCell.swift
  PLUB/Sources/Views/Home/Archive/ArchiveViewController.swift
  PLUB/Sources/Views/Home/Archive/ArchiveViewModel.swift
Labels: 🍎 ConfigureUI, 🥳MainPage

#203 [FEAT] 메인페이지 UI 코드
  PLUB.xcodeproj/project.pbxproj
  PLUB/Sources/Views/Home/MainPage/BoardViewController.swift
  PLUB/Sources/Views/Home/MainPage/Cell/BoardClipboardHeaderView.swift
  PLUB/Sources/Views/Home/MainPage/Cell/BoardCollectionHeaderView.swift
  PLUB/Sources/Views/Home/MainPage/Cell/MainPageClipboardCollectionViewCell.swift
  PLUB/Sources/Views/Home/MainPage/Component/ClipboardListView.swift
  PLUB/Sources/Views/Home/MainPage/MainPageViewController.swift
  PLUB/Sources/Views/Home/MainPage/ViewModel/BoardViewModel.swift
  PLUB/Sources/Views/Home/MainPage/ViewModel/MainPageViewModel.swift
Labels: 🍎 ConfigureUI, D+0, 🥳MainPage

#206 [CHORE] 메인페이지화면이동코드 추가
  PLUB/Sources/Views/Home/HomeViewController.swift
  PLUB/Sources/Views/Meeting/MeetingViewController.swift
Labels: 😎 Enhancement

#207 [FEAT] Clipboard API 연동 및 버그 수정
  PLUB.xcodeproj/project.pbxproj
  PLUB/Sources/Models/Feeds/FeedsContent.swift
  PLUB/Sources/Views/Home/Clipboard/ClipboardViewController.swift
  PLUB/Sources/Views/Home/Clipboard/Model/BoardModel.swift
  PLUB/Sources/Views/Home/Clipboard/ViewModel/BoardDetailViewModel.swift
  PLUB/Sources/Views/Home/Clipboard/ViewModel/ClipboardViewModel.swift
  PLUB/Sources/Views/PLUBTabBarController.swift
Labels: 😎 Enhancement, 🥳MainPage

#212 [CHORE] BoardModel 프로퍼티 수정
  PLUB/Sources/Views/Home/Clipboard/Model/BoardModel.swift
Labels: 😎 Enhancement, D+0

#213 [DEL] Default value in BoardModel
  PLUB/Sources/Views/Home/Clipboard/Model/BoardModel.swift
  PLUB/Sources/Views/Home/MainPage/BoardViewController.swift
  PLUB/Sources/Views/Home/MainPage/ViewModel/MainPageViewModel.swift
Labels: 🐛 bug

#214 [Feat] 마이페이지 메인 화면 구현
  PLUB.xcodeproj/project.pbxproj
  PLUB/Assets.xcassets/MyPage/Contents.json
  PLUB/Assets.xcassets/MyPage/foldedArrow.imageset/Contents.json
  PLUB/Assets.xcassets/MyPage/foldedArrow.imageset/unfoldedArrow.png
  PLUB/Assets.xcassets/MyPage/foldedArrow.imageset/unfoldedArrow@2x.png
  PLUB/Assets.xcassets/MyPage/foldedArrow.imageset/unfoldedArrow@3x.png
  PLUB/Assets.xcassets/MyPage/pencil.imageset/Contents.json
  PLUB/Assets.xcassets/MyPage/pencil.imageset/pencil.png
  PLUB/Assets.xcassets/MyPage/pencil.imageset/pencil@2x.png
  PLUB/Assets.xcassets/MyPage/pencil.imageset/pencil@3x.png
  PLUB/Assets.xcassets/MyPage/setting.imageset/Contents.json
  PLUB/Assets.xcassets/MyPage/setting.imageset/setting.png
  PLUB/Assets.xcassets/MyPage/setting.imageset/setting@2x.png
  PLUB/Assets.xcassets/MyPage/setting.imageset/setting@3x.png
  PLUB/Assets.xcassets/MyPage/unfoldedArrow.imageset/Contents.json
  PLUB/Assets.xcassets/MyPage/unfoldedArrow.imageset/unfoldedArrow.png
  PLUB/Assets.xcassets/MyPage/unfoldedArrow.imageset/unfoldedArrow@2x.png
  PLUB/Assets.xcassets/MyPage/unfoldedArrow.imageset/unfoldedArrow@3x.png
  PLUB/Configuration/Extensions/Ex+CALayer.swift
  PLUB/Configuration/Extensions/Ex+UIColor.swift
  PLUB/Sources/Models/Account/Response/MyInfoResponse.swift
  PLUB/Sources/Models/MyPage/Request/MyPlubbingParameter.swift
  PLUB/Sources/Models/MyPage/Response/MyPlubbingResponse.swift
  PLUB/Sources/Network/Routers/AccountRouter.swift
  PLUB/Sources/Network/Routers/MyPageRouter.swift
  PLUB/Sources/Network/Services/AccountService.swift
  PLUB/Sources/Network/Services/MyPageService.swift
  PLUB/Sources/Views/Meeting/MeetingViewController.swift
  PLUB/Sources/Views/Meeting/Schedule/CreateSchedule/Component/ScheduleAlarmView.swift
  PLUB/Sources/Views/MyPage/Cell/MyPageSectionFooterView.swift
  PLUB/Sources/Views/MyPage/Cell/MyPageSectionHeaderView.swift
  PLUB/Sources/Views/MyPage/Cell/MyPageTableViewCell.swift
  PLUB/Sources/Views/MyPage/Component/MyProfileView.swift
  PLUB/Sources/Views/MyPage/MyPageViewController.swift
  PLUB/Sources/Views/MyPage/MyPageViewModel.swift
  PLUB/Sources/Views/PLUBTabBarController.swift
Labels: 🍎 ConfigureUI, D+1, 👤 MyPage

#215 댓글 API 연동
  PLUB/Sources/Models/Feeds/CommentContent.swift
  PLUB/Sources/Models/Feeds/FeedsContent.swift
  PLUB/Sources/Views/Home/Clipboard/BoardDetailViewController.swift
  PLUB/Sources/Views/Home/Clipboard/Cell/BoardDetailCollectionViewCell.swift
  PLUB/Sources/Views/Home/Clipboard/ClipboardViewController.swift
  PLUB/Sources/Views/Home/Clipboard/Component/BoardDetailCollectionHeaderView.swift
  PLUB/Sources/Views/Home/Clipboard/ViewModel/BoardDetailViewModel.swift
Labels: 😎 Enhancement, 🍎 ConfigureUI, D+1, 🥳MainPage

#216 [FEAT] 메인페이지 게시판 UI 레이아웃 및 API 연동
  PLUB.xcodeproj/project.pbxproj
  PLUB/Configuration/Extensions/Ex+Date.swift
  PLUB/Sources/Views/Home/MainPage/BoardViewController.swift
  PLUB/Sources/Views/Home/MainPage/Cell/BoardClipboardHeaderView.swift
  PLUB/Sources/Views/Home/MainPage/Cell/BoardSystemCollectionViewCell.swift
  PLUB/Sources/Views/Home/MainPage/Cell/MainPageClipboardView.swift
  PLUB/Sources/Views/Home/MainPage/MainPageViewController.swift
  PLUB/Sources/Views/Home/MainPage/ViewModel/BoardViewModel.swift
  PLUB/Sources/Views/Meeting/MeetingViewController.swift
Labels: 😎 Enhancement, 🍎 ConfigureUI, D+0, 🥳MainPage

#217 [FIX] 일부 페이징 API, 커서 기반 페이지네이션으로 수정
  PLUB/Sources/Network/Routers/FeedsRouter.swift
  PLUB/Sources/Network/Services/FeedsService.swift
Labels: 🔥hotfix

#218 [FIX] Alamofire retry 내부 로직 수정
  PLUB/Sources/Network/Foundation/Interceptor.swift
Labels: 🔥hotfix

#221 [FEAT] 메인페이지 게시글 생성 화면
  PLUB.xcodeproj/project.pbxproj
  PLUB/SceneDelegate.swift
  PLUB/Sources/Views/Home/MainPage/BoardViewController.swift
  PLUB/Sources/Views/Home/MainPage/CreateBoardViewController.swift
  PLUB/Sources/Views/Home/MainPage/MainPageViewController.swift
  PLUB/Sources/Views/Home/MainPage/ViewModel/CreateBoardViewModel.swift
Labels: 😎 Enhancement, 🍎 ConfigureUI, D+1, 🥳MainPage

#224 [FEAT] 메인페이지 스크롤에 따른 플로팅버튼 구현
  PLUB/Sources/Views/Home/MainPage/CreateBoardViewController.swift
  PLUB/Sources/Views/Home/MainPage/MainPageViewController.swift
Labels: 😎 Enhancement, 🍎 ConfigureUI, D+0

#222 [FEAT] 마이페이지 > 모집 중인 모임 기능 구현
  PLUB.xcodeproj/project.pbxproj
  PLUB/Sources/Models/Recruitment/Response/InquireApplicantResponse.swift
  PLUB/Sources/Network/Routers/RecruitmentRouter.swift
  PLUB/Sources/Network/Services/RecruitmentService.swift
  PLUB/Sources/Views/MyPage/Component/MyPageNoneView.swift
  PLUB/Sources/Views/MyPage/MyPageViewController.swift
  PLUB/Sources/Views/MyPage/MyPageViewModel.swift
  PLUB/Sources/Views/MyPage/Recruiting/Cell/RecruitingSectionFooterView.swift
  PLUB/Sources/Views/MyPage/Recruiting/Cell/RecruitingSectionHeaderView.swift
  PLUB/Sources/Views/MyPage/Recruiting/Cell/RecruitingTableViewCell.swift
  PLUB/Sources/Views/MyPage/Recruiting/Component/CustomAlertView.swift
  PLUB/Sources/Views/MyPage/Recruiting/Component/RecruitingFooterView.swift
  PLUB/Sources/Views/MyPage/Recruiting/Component/RecruitingHeaderView.swift
  PLUB/Sources/Views/MyPage/Recruiting/RecruitingViewController.swift
  PLUB/Sources/Views/MyPage/Recruiting/RecruitingViewModel.swift
Labels: 🍎 ConfigureUI, D+1, 👤 MyPage

#226 [FEAT] 설정 UI 작업
  PLUB.xcodeproj/project.pbxproj
  PLUB/Assets.xcassets/MyPage/arrowRightGray.imageset/Contents.json
  PLUB/Assets.xcassets/MyPage/arrowRightGray.imageset/arrowRightGray.png
  PLUB/Assets.xcassets/MyPage/arrowRightGray.imageset/arrowRightGray@2x.png
  PLUB/Assets.xcassets/MyPage/arrowRightGray.imageset/arrowRightGray@3x.png
  PLUB/Sources/Views/MyPage/MyPageViewController.swift
  PLUB/Sources/Views/MyPage/Setting/Component/SettingDetailSubView.swift
  PLUB/Sources/Views/MyPage/Setting/Component/SettingSubview.swift
  PLUB/Sources/Views/MyPage/Setting/SettingViewController.swift
Labels: 🍎 ConfigureUI, 👤 MyPage

#227 [Network] 댓글 API 수정
  PLUB/Sources/Models/Feeds/CommentContent.swift
  PLUB/Sources/Views/Home/Clipboard/Cell/BoardDetailCollectionViewCell.swift
Labels: 😎 Enhancement, D+0, 🥳MainPage

#228 BoardDetailViewModel's initializer 수정
  PLUB/Sources/Views/Home/Clipboard/BoardDetailViewController.swift
  PLUB/Sources/Views/Home/Clipboard/ClipboardViewController.swift
  PLUB/Sources/Views/Home/Clipboard/ViewModel/BoardDetailViewModel.swift
Labels: 😎 Enhancement, D+0, 🥳MainPage

#230 [FEAT] 지원화면 및 모집글 세부화면 수정
  PLUB.xcodeproj/project.pbxproj
  PLUB/Assets.xcassets/Home/Component/editBlack.imageset/Contents.json
  PLUB/Assets.xcassets/Home/Component/editBlack.imageset/akar-icons_edit.png
  PLUB/Assets.xcassets/Home/Component/editBlack.imageset/akar-icons_edit@2x.png
  PLUB/Assets.xcassets/Home/Component/editBlack.imageset/akar-icons_edit@3x.png
  PLUB/Assets.xcassets/Home/Component/lightBeaconMain.imageset/Component 2.png
  PLUB/Assets.xcassets/Home/Component/lightBeaconMain.imageset/Component 2@2x.png
  PLUB/Assets.xcassets/Home/Component/lightBeaconMain.imageset/Component 2@3x.png
  PLUB/Assets.xcassets/Home/Component/lightBeaconMain.imageset/Contents.json
  PLUB/Assets.xcassets/Home/Component/pinBlack.imageset/Contents.json
  PLUB/Assets.xcassets/Home/Component/pinBlack.imageset/bx_pin.png
  PLUB/Assets.xcassets/Home/Component/pinBlack.imageset/bx_pin@2x.png
  PLUB/Assets.xcassets/Home/Component/pinBlack.imageset/bx_pin@3x.png
  PLUB/Assets.xcassets/Home/Component/trashRed.imageset/Contents.json
  PLUB/Assets.xcassets/Home/Component/trashRed.imageset/Vector.png
  PLUB/Assets.xcassets/Home/Component/trashRed.imageset/Vector@2x.png
  PLUB/Assets.xcassets/Home/Component/trashRed.imageset/Vector@3x.png
  PLUB/Configuration/Extensions/Ex+UIButton.swift
  PLUB/Sources/Models/Meeting/Response/CategoryMeetingResponse.swift
  PLUB/Sources/Models/Recruitment/Request/ApplyForRecruitmentRequest.swift
  PLUB/Sources/Models/Recruitment/Response/ApplyForRecruitmentResponse.swift
  PLUB/Sources/Network/Routers/MeetingRouter.swift
  PLUB/Sources/Network/Routers/RecruitmentRouter.swift
  PLUB/Sources/Network/Services/MeetingService.swift
  PLUB/Sources/Network/Services/RecruitmentService.swift
  PLUB/Sources/Views/Home/ApplyQuestionViewController.swift
  PLUB/Sources/Views/Home/BookmarkViewController.swift
  PLUB/Sources/Views/Home/Cell/ApplyQuestion/ApplyQuestionTableViewCell.swift
  PLUB/Sources/Views/Home/Cell/SelectCategory/SelectedCategoryChartCollectionViewCell.swift
  PLUB/Sources/Views/Home/Cell/SelectCategory/SelectedCategoryGridCollectionViewCell.swift
  PLUB/Sources/Views/Home/Clipboard/Cell/BoardCollectionViewCell.swift
  PLUB/Sources/Views/Home/Component/HomeAlert.swift
  PLUB/Sources/Views/Home/DetailRecruitmentViewController.swift
  PLUB/Sources/Views/Home/HomeViewController.swift
  PLUB/Sources/Views/Home/MainPage/BoardViewController.swift
  PLUB/Sources/Views/Home/MainPage/Cell/BoardClipboardHeaderView.swift
  PLUB/Sources/Views/Home/MainPage/Component/BoardBottomSheetViewController.swift
  PLUB/Sources/Views/Home/MainPage/MainPageViewController.swift
  PLUB/Sources/Views/Home/MainPage/ViewModel/BoardViewModel.swift
  PLUB/Sources/Views/Home/SearchInputViewController.swift
  PLUB/Sources/Views/Home/SelectedCategoryViewController.swift
  PLUB/Sources/Views/Home/ViewModel/ApplyQuestionViewModel.swift
  PLUB/Sources/Views/Home/ViewModel/BookmarkViewModel.swift
  PLUB/Sources/Views/Home/ViewModel/DetailRecruitmentViewModel.swift
  PLUB/Sources/Views/Home/ViewModel/HomeViewModel.swift
  PLUB/Sources/Views/Home/ViewModel/SearchInputViewModel.swift
  PLUB/Sources/Views/Home/ViewModel/SelectedCategoryViewModel.swift
  PLUB/Sources/Views/Meeting/CreateMeeting/Component/PhotoBottomSheetListView.swift
  PLUB/Sources/Views/Meeting/EditMeeting/EditMeetingViewController.swift
  PLUB/Sources/Views/Meeting/EditMeeting/EditMeetingViewModel.swift
  PLUB/Sources/Views/Meeting/EditMeeting/ViewModel/GuestQuestionViewModel.swift
  PLUB/Sources/Views/Meeting/EditMeeting/ViewModel/MeetingInfoViewModel.swift
  PLUB/Sources/Views/Meeting/EditMeeting/ViewModel/RecruitPostViewModel.swift
  PLUB/Sources/Views/MyPage/Recruiting/RecruitingViewController.swift
  PLUB/Sources/Views/MyPage/Recruiting/RecruitingViewModel.swift
Labels: 😎 Enhancement, 🍎 ConfigureUI, 🏠 Home, 🥳MainPage

#236 Figma에 맞게 색상 재설정
  PLUB/Configuration/Extensions/Ex+UIColor.swift
Labels: 🍎 ConfigureUI, D+1

#234 [ADD] 게시판상세화면이동코드 추가
  PLUB/Sources/Views/Home/MainPage/BoardViewController.swift
  PLUB/Sources/Views/Home/MainPage/MainPageViewController.swift
  PLUB/Sources/Views/Home/MainPage/ViewModel/BoardViewModel.swift
Labels: 😎 Enhancement, 🥳MainPage

#235 게시판 댓글 생성 UI 구현
  PLUB.xcodeproj/project.pbxproj
  PLUB/Assets.xcassets/Home/Clipboard/arrowUpFilledCircle.imageset/Contents.json
  PLUB/Assets.xcassets/Home/Clipboard/arrowUpFilledCircle.imageset/arrowUpFilledCircle.png
  PLUB/Assets.xcassets/Home/Clipboard/arrowUpFilledCircle.imageset/arrowUpFilledCircle@2x.png
  PLUB/Assets.xcassets/Home/Clipboard/arrowUpFilledCircle.imageset/arrowUpFilledCircle@3x.png
  PLUB/Sources/Views/Home/Clipboard/BoardDetailViewController.swift
  PLUB/Sources/Views/Home/Clipboard/Component/CommentInputView.swift
Labels: 🍎 ConfigureUI, D+1, 🥳MainPage

#238 [FEAT] 내모임 UI 구현
  PLUB.xcodeproj/project.pbxproj
  PLUB/Assets.xcassets/Meeting/MyMeeting/Contents.json
  PLUB/Assets.xcassets/Meeting/MyMeeting/menuWhite.imageset/Contents.json
  PLUB/Assets.xcassets/Meeting/MyMeeting/menuWhite.imageset/menuWhite.png
  PLUB/Assets.xcassets/Meeting/MyMeeting/menuWhite.imageset/menuWhite@2x.png
  PLUB/Assets.xcassets/Meeting/MyMeeting/menuWhite.imageset/menuWhite@3x.png
  PLUB/Assets.xcassets/Meeting/MyMeeting/plusCircle.imageset/Contents.json
  PLUB/Assets.xcassets/Meeting/MyMeeting/plusCircle.imageset/plusCircle.png
  PLUB/Assets.xcassets/Meeting/MyMeeting/plusCircle.imageset/plusCircle@2x.png
  PLUB/Assets.xcassets/Meeting/MyMeeting/plusCircle.imageset/plusCircle@3x.png
  PLUB/Configuration/Extensions/Ex+UIImage.swift
  PLUB/Sources/Views/Meeting/Cell/MeetingCollectionMoreCell.swift
  PLUB/Sources/Views/Meeting/Cell/MeetingCollectionViewCell.swift
  PLUB/Sources/Views/Meeting/Component/MeetingTypeControl.swift
  PLUB/Sources/Views/Meeting/MeetingViewController.swift
  PLUB/Sources/Views/Meeting/MeetingViewModel.swift
Labels: 🍎 ConfigureUI, 👨‍👩‍👧‍👦 Meeting, D+1

#241 댓글 작성 기능 구현
  PLUB/Sources/Network/Services/FeedsService.swift
  PLUB/Sources/Views/Home/Clipboard/BoardDetailViewController.swift
  PLUB/Sources/Views/Home/Clipboard/ViewModel/BoardDetailViewModel.swift
Labels: 😎 Enhancement, 🍎 ConfigureUI, D+1, 🥳MainPage

#242 댓글 페이징 구현
  PLUB/Sources/Models/Feeds/CommentContent.swift
  PLUB/Sources/Views/Home/Clipboard/BoardDetailViewController.swift
  PLUB/Sources/Views/Home/Clipboard/ViewModel/BoardDetailViewModel.swift
Labels: 🍎 ConfigureUI, D+1, 🥳MainPage
